/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menghitung.volume;

import javax.swing.JOptionPane;

/**
 *
 * @author -asus-
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        intT = new javax.swing.JTextField();
        intP = new javax.swing.JTextField();
        intL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitBa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        intS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hitKu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        intR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hitBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 400, 50);

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Tinggi     :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 210, 30);

        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 130, 80, 30);

        jLabel4.setText("Masukkan Lebar     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 80, 210, 30);
        jPanel1.add(intT);
        intT.setBounds(210, 130, 190, 30);
        jPanel1.add(intP);
        intP.setBounds(210, 30, 190, 30);
        jPanel1.add(intL);
        intL.setBounds(210, 80, 190, 30);

        jLabel5.setText("Masukkan Panjang :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 30, 210, 30);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 30, 80, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(410, 80, 80, 30);

        hitBa.setBackground(new java.awt.Color(102, 102, 102));
        hitBa.setText("Hitung Volume");
        hitBa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitBaActionPerformed(evt);
            }
        });
        jPanel1.add(hitBa);
        hitBa.setBounds(210, 180, 190, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(160, 70, 210, 30);
        jPanel2.add(intS);
        intS.setBounds(160, 110, 190, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(360, 110, 80, 30);

        hitKu.setBackground(new java.awt.Color(102, 102, 102));
        hitKu.setText("Hitung Volume");
        hitKu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitKuActionPerformed(evt);
            }
        });
        jPanel2.add(hitKu);
        hitKu.setBounds(160, 150, 190, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari-jari :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(160, 70, 210, 30);
        jPanel3.add(intR);
        intR.setBounds(160, 110, 190, 30);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(360, 110, 80, 30);

        hitBo.setBackground(new java.awt.Color(102, 102, 102));
        hitBo.setText("Hitung Volume");
        hitBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitBoActionPerformed(evt);
            }
        });
        jPanel3.add(hitBo);
        hitBo.setBounds(160, 150, 190, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 530, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitBaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitBaActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(intP.getText());
        lebar = Integer.parseInt(intL.getText());
        tinggi = Integer.parseInt(intT.getText());
        int hasil = panjang * lebar * tinggi;

        try{
            JOptionPane.showMessageDialog(null, "Volume Balok : "+hasil,"luas"
                , JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitBaActionPerformed

    private void hitKuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitKuActionPerformed
        // TODO add your handling code here:

        int sisi;
        sisi = Integer.parseInt(intS.getText());
        int hasil = sisi * sisi * sisi;

        try{
            JOptionPane.showMessageDialog(null, "Luas Permukaan Kubus Adalah : "
                +hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitKuActionPerformed

    private void hitBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitBoActionPerformed
        // TODO add your handling code here:

        float jari;
        jari = Integer.parseInt(intR.getText());
        float hasil1 = (float) (4/3*3.14*jari*jari*jari);

        try{
            JOptionPane.showMessageDialog(null, "Luas Permukaan Bola Adalah : "
                +hasil1, "luas", JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e, "Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitBoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitBa;
    private javax.swing.JButton hitBo;
    private javax.swing.JButton hitKu;
    private javax.swing.JTextField intL;
    private javax.swing.JTextField intP;
    private javax.swing.JTextField intR;
    private javax.swing.JTextField intS;
    private javax.swing.JTextField intT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
